name: hello-world
#on: push
on: 
  workflow_dispatch:
    inputs:
      test:
        required: true
        default: 'please'
  


jobs:
  my-job1:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo '${{ inputs.test }} ${{ secrets.msg }}'
