name: hello-world
#on: push
on: 
  workflow_call:
    inputs:
      test:
        required: true
        default: please
        type: string
  


jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World! ${{ inputs.test }}"
