#name: hello-world
#on: push
#on: 
  #workflow_dispatch:
    #inputs:
      #test:
        #required: true
        #default: 'please'
  


#jobs:
  #my-job1:
    #runs-on: ubuntu-latest
    #steps:
      #- name: my-step
        #run: echo '${{ inputs.test }} ${{ secrets.msg }}'
on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
           {
             "key": "value",
             "foo": "bar"
           }
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    #- uses: actions/checkout@v2
    #- name: Slack Notification
      #uses: rtCamp/action-slack-notify@v2
      #env:
        #SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
